seed = 1
batch_size = 64
patience = 16
n_epochs = inf

[data]
seed = 0
cache = true
path = ":data/classif-cat-medium-1-KDDCup09_upselling"
num_policy = "quantile"
cat_policy = "ordinal"
y_policy = "__null__"

[optimizer]
type = "AdamW"
lr = 8.17147891511587e-05
weight_decay = 0.0

[model.backbone]
type = "MLP"
n_blocks = 4
d_layer = 652
dropout = 0.3409101495517417
activation = "ReLU"

[model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 45
frequency_scale = 0.559922365406335
d_embedding = 50
lite = false
