seed = 10

[data]
seed = 0
num_policy = "__null__"
cat_policy = "__null__"
cache = true
path = ":data/regression-cat-medium-3-Mercedes_Benz_Greener_Manufacturing"
y_policy = "standard"

[model]
iterations = 4000
early_stopping_rounds = 200
od_pval = 0.001
bagging_temperature = 0.21405693979874302
depth = 4
l2_leaf_reg = 8.944302332821092
leaf_estimation_iterations = 2
learning_rate = 0.0224389298517171
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"
