seed = 0
function = "bin.xgboost_.main"
n_trials = 200
timeout = "__null__"

[sampler]
n_startup_trials = 20

[space]
seed = 0

[space.data]
seed = 0
num_policy = "__null__"
cache = true
path = ":data/regression-cat-medium-3-Mercedes_Benz_Greener_Manufacturing"
cat_policy = "one-hot"
y_policy = "standard"

[space.model]
booster = "gbtree"
n_estimators = 4000
n_jobs = 1
tree_method = "gpu_hist"
use_label_encoder = false
colsample_bytree = [
    "_tune_",
    "uniform",
    0.5,
    1.0,
]
gamma = [
    "_tune_",
    "?loguniform",
    0,
    0.001,
    100.0,
]
lambda = [
    "_tune_",
    "?loguniform",
    0.0,
    0.1,
    10.0,
]
learning_rate = [
    "_tune_",
    "loguniform",
    0.001,
    1.0,
]
max_depth = [
    "_tune_",
    "int",
    3,
    14,
]
min_child_weight = [
    "_tune_",
    "loguniform",
    0.0001,
    100.0,
]
subsample = [
    "_tune_",
    "uniform",
    0.5,
    1.0,
]

[space.fit]
early_stopping_rounds = 200
verbose = true
