seed = 2

[data]
seed = 0
num_policy = "__null__"
cache = true
path = ":data/regression-cat-medium-4-analcatdata_supreme"
cat_policy = "__null__"
y_policy = "standard"

[model]
n_estimators = 4000
n_jobs = 4
feature_fraction = 0.6553903826646611
lambda_l2 = 0.46642131726655084
learning_rate = 0.7154945356709238
num_leaves = 507
min_sum_hessian_in_leaf = 71.51432910097532
bagging_fraction = 0.525867140615026

[fit]
early_stopping_rounds = 200
verbose = true
