seed = 0
function = "bin.dkl.main"
n_trials = 100
timeout = "__null__"

[sampler]

[space]
seed = 0
kernel = [
    "_tune_",
    "categorical",
    [
        "rbf",
        "sm",
    ],
]
lr = [
    "_tune_",
    "loguniform",
    1e-05,
    0.01,
]
weight_decay = [
    "_tune_",
    "?loguniform",
    0.0,
    1e-06,
    0.001,
]
patience = 16
n_epochs = inf

[space.data]
seed = 0
cache = true
path = ":data/california"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"

[space.mlp]
n_blocks = [
    "_tune_",
    "int",
    1,
    4,
]
d_layer = [
    "_tune_",
    "int",
    64,
    768,
]
dropout = [
    "_tune_",
    "?uniform",
    0.0,
    0.0,
    0.5,
]
activation = "ReLU"
