seed = 9
batch_size = 32
patience = 16
n_epochs = inf
context_size = 96

[data]
seed = 0
cache = true
path = ":data/classif-num-medium-1-phoneme"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"

[model]
num_embeddings = "__null__"
d_main = 225
context_dropout = 0.011273880261813085
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.3705812982455262
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 0.00025660719000930555
weight_decay = 2.3101522250182388e-05
