seed = 0
function = "bin.anp.main"
n_trials = 20
timeout = "__null__"

[sampler]

[space]
seed = 0
batch_size = 512
patience = 16
n_epochs = inf
num_accumulate = 1
eval_batch_size = 4096
eval_batch_size_context = 32000

[space.data]
seed = 0
cache = true
path = ":data/black-friday"
num_policy = "quantile"
cat_policy = "ordinal"
y_policy = "standard"

[space.model]
num_embeddings = "__null__"
d_hidden = [
    "_tune_",
    "int",
    96,
    384,
]
num_layers_dec = [
    "_tune_",
    "int",
    1,
    3,
]
num_self_attention_l = [
    "_tune_",
    "int",
    1,
    2,
]
num_cross_attention_l = [
    "_tune_",
    "int",
    1,
    2
]

[space.optimizer]
type = "AdamW"
lr = [
    "_tune_",
    "loguniform",
    1e-05,
    0.001,
]
weight_decay = [
    "_tune_",
    "?loguniform",
    0.001,
    1e-06,
    0.0001,
]
