[data]
seed = 0
cache = true
path = ":data/diamond"
num_policy = "quantile"
cat_policy = "one-hot"
y_policy = "standard"

[dnnr]
n_neighbors = [
    1,
    129,
]
n_derivative_neighbors = [
    52,
    364,
    14,
]
scalings_dir = "dnnr/precomputed_scaling/diamond/ohe"
