seed = 0
function = "bin.lightgbm_.main"
n_trials = 200
timeout = "__null__"

[sampler]
n_startup_trials = 20

[space]
seed = 0

[space.data]
seed = 0
num_policy = "__null__"
cache = true
path = ":data/microsoft"
cat_policy = "__null__"
y_policy = "standard"

[space.model]
n_estimators = 4000
n_jobs = 4
feature_fraction = [
    "_tune_",
    "uniform",
    0.5,
    1.0,
]
lambda_l2 = [
    "_tune_",
    "?loguniform",
    0.0,
    0.1,
    10.0,
]
learning_rate = [
    "_tune_",
    "loguniform",
    0.001,
    1.0,
]
num_leaves = [
    "_tune_",
    "int",
    4,
    768,
]
min_sum_hessian_in_leaf = [
    "_tune_",
    "loguniform",
    0.0001,
    100.0,
]
bagging_fraction = [
    "_tune_",
    "uniform",
    0.5,
    1.0,
]

[space.fit]
early_stopping_rounds = 200
verbose = true
