[data]
seed = 0
cache = true
path = ":data/california"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"

[dnnr]
n_neighbors = [
    1,
    129,
]
n_derivative_neighbors = [
    16,
    144,
    20,
]
scalings_dir = "dnnr/precomputed_scaling/california/loo"
