seed = 0
batch_size = 256
patience = 16
n_epochs = inf

[data]
seed = 0
cache = true
path = ":data/regression-num-medium-0-houses"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"

[optimizer]
type = "AdamW"
lr = 0.0008242053761924815
weight_decay = 0.0

[model]
num_embeddings = "__null__"

[model.backbone]
type = "MLP"
n_blocks = 3
d_layer = 183
dropout = 0.07704096986714269
activation = "ReLU"
