seed = 3

[data]
seed = 0
num_policy = "__null__"
cache = true
path = ":data/higgs-small"
cat_policy = "__null__"
y_policy = "__null__"

[model]
n_estimators = 4000
n_jobs = 4
feature_fraction = 0.7617617929747057
lambda_l2 = 0.2762162431850233
learning_rate = 0.012254446458263379
num_leaves = 333
min_sum_hessian_in_leaf = 0.00012586244235412866
bagging_fraction = 0.8955418186524106

[fit]
early_stopping_rounds = 200
verbose = true
