seed = 4
batch_size = 128
patience = 16
n_epochs = inf

[data]
seed = 0
cache = true
path = ":data/classif-num-medium-2-bank-marketing"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"

[optimizer]
type = "AdamW"
lr = 3.552376211394028e-05
weight_decay = 0.0

[model.backbone]
type = "MLP"
n_blocks = 5
d_layer = 139
dropout = 0.0
activation = "ReLU"

[model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 43
frequency_scale = 0.10935830579655947
d_embedding = 52
lite = false
