[data]
seed = 0
cache = true
path = ":data/diamond"
num_policy = "quantile"
cat_policy = "ordinal"
y_policy = "standard"

[dnnr]
n_neighbors = [
    1,
    129,
]
n_derivative_neighbors = [
    18,
    126,
    14,
]
scalings_dir = "dnnr/precomputed_scaling/diamond/loo"
