seed = 8
batch_size = 256
patience = 16
n_epochs = inf
context_size = 96

[data]
seed = 0
cache = true
path = ":data/classif-num-medium-0-credit"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"

[model]
num_embeddings = "__null__"
d_main = 192
context_dropout = 0.39031512502137305
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.4408085841583972
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 0.00017823786944316954
weight_decay = 1.6890838302308978e-05
