seed = 3
batch_size = 64
patience = 16
n_epochs = inf
context_size = 96

[data]
seed = 0
cache = true
path = ":data/regression-cat-medium-3-analcatdata_supreme"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"

[model]
d_main = 262
context_dropout = 0.26447652629464125
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 2
mixer_normalization = "auto"
dropout0 = 0.31115631501811186
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 63
frequency_scale = 0.5102579007226918
d_embedding = 25
lite = true

[optimizer]
type = "AdamW"
lr = 0.0004211298007342421
weight_decay = 0.0
