seed = 0
function = "bin.catboost_.main"
n_trials = 200
timeout = "__null__"

[sampler]
n_startup_trials = 20

[space]
seed = 0

[space.data]
seed = 0
num_policy = "__null__"
cat_policy = "__null__"
cache = true
path = ":data/microsoft"
y_policy = "standard"

[space.model]
iterations = 4000
early_stopping_rounds = 200
od_pval = 0.001
bagging_temperature = [
    "_tune_",
    "uniform",
    0.0,
    1.0,
]
depth = [
    "_tune_",
    "int",
    3,
    14,
]
l2_leaf_reg = [
    "_tune_",
    "uniform",
    0.1,
    10.0,
]
leaf_estimation_iterations = [
    "_tune_",
    "int",
    1,
    10,
]
learning_rate = [
    "_tune_",
    "loguniform",
    0.001,
    1.0,
]
task_type = "GPU"
thread_count = 1

[space.fit]
logging_level = "Verbose"
