seed = 1
batch_size = 32
patience = 16
n_epochs = inf

[data]
seed = 0
cache = true
path = ":data/classif-num-medium-3-wine"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"

[optimizer]
type = "AdamW"
lr = 8.374496868436811e-05
weight_decay = 0.0

[model.backbone]
type = "MLP"
n_blocks = 4
d_layer = 201
dropout = 0.0
activation = "ReLU"

[model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 49
frequency_scale = 0.11434638743472199
d_embedding = 53
lite = false
